### ISSUE TITLE
hmFS.stat, hmFS.stat_asset and hmFS.open, hmFS.open_asset confusion.

### ISSUE THREAD

**Issue by bbComputerdd** [melianmiko/ZeppPlayer#3]
In the simulator, `hmFS.stat` and `hmFS.stat_asset` have the same function. So do `hmFS.open` and `hmFS.open_asset`. Which is not match the situation of the physical machine(Mi Band 7). Actually, they read or open files from different directories.

- `hmFS.stat` and `hmFS.open` point to `js_watchfaces/data/(appid)` or `js_apps/data/(appid)` directory.
- `hmFS.stat_asset` and `hmFS.open_asset` point to `js_watchfaces/(appid)/asset` or `js_apps/data(appid)/asset` directory.

Is there any possibility to introduce real features related to `/data`. Or display a warning message in the console when using `hmFS.stat` and `hmFS.open`?

**Comment by melianmiko** [comment]
Hi,

Looks like you're using very old version of ZeppPlayer, this behavior was [already fixed](https://github.com/melianmiko/ZeppPlayer/blob/cab6e111011f76bdd3b6759c066cb14dc1e80ddf/src/zepp_player/zepp_env/HuamiFs.js#L65) since version 1.6.10.

**Comment by bbComputerdd** [comment]
Oh, I just notice that the auto update was disabled. Problem solved after updating. Thanks a lot.
